### ISSUE TITLE
Remove old guidance on publication sharing

### ISSUE THREAD

**Issue by RPaseka** [nasa/smd-open-science-guidelines#11]
The original guidance on publications
smd-open-science-guidelines/guidance/research_publications.md

has now been replaced with 
smd-open-science-guidelines/OSS_Guidance/Publications.md

We should remove the old guidance or somehow indicate that it has been replaced since it is less comprehensive than the new version. For review by @nasacrawford

**Comment by nasacrawford** [comment]
File was removed in [c05dd52](https://github.com/nasa/smd-open-science-guidelines/commit/c05dd521034999812a04f9f568eb3a70e0b7ea0a) with a comment pointing to the most recent version.
