### ISSUE TITLE
Data guidance expansion

### ISSUE THREAD

**Issue by RPaseka** [nasa/smd-open-science-guidelines#18]
Expand current guidance on [data management and sharing](https://github.com/nasa/smd-open-science-guidelines/blob/main/OSS_Guidance/Data_Management_Sharing.md#where-to-share-data) to include:
- [ ] #24
- [ ] #25
- [ ] #26

**Comment by nasacrawford** [comment]
I might suggest creating a new issue for each of these.

**Comment by RPaseka** [comment]
These items are now broken into their own issues, so I'm closing the original one.
