### ISSUE TITLE
Broken data.nasa.gov link

### ISSUE THREAD

**Issue by rfergason** [nasa/smd-open-science-guidelines#34]
The below link is currently broken in this documentation:
https://github.com/nasa/smd-open-science-guidelines/blob/main/OSS_Guidance/data.nasa.gov

This may be due to the NASA web migration switch, as the transition from beta to primary occurred last week.  So, there may be other links that are broken as well.

**Comment by rfergason** [comment]
This link is also broken:  https://science.nasa.gov/science-red/s3fs-public/atoms/files/SMD-information-policy-SPD-41a.pdf

This was noted under section Where to Share Data - https://github.com/nasa/smd-open-science-guidelines/blob/main/OSS_Guidance/Data_Management_Sharing.md#where-to-share-data

It is likely that the link to SPD-41a may be broken in other places as well.

**Comment by RPaseka** [comment]
Thanks for noting this, @rfergason. You're correct that this is a web migration issue and that there are additional broken links in this guidance (e.g., most of the SMD division policies). We're in touch with the web team about fixing these, and I'll update here once this has happened.

**Comment by RPaseka** [comment]
We fixed the links to SPD-41a and the SMD division policies, [documented here](https://github.com/nasa/smd-open-science-guidelines/pull/36).
