### ISSUE TITLE
update guideline when final policy is release

### ISSUE THREAD

**Issue by chutneyboy** [nasa/smd-open-science-guidelines#4]
The RFC you are commenting on: **Registration of DOIs for data citation**

Type of comment:
- [ ] Editorial - grammar, spelling, word choice, etc.
- [x] Minor - would not affect the overall direction of the guideline but could provide clarity, a small correction, a minor change to process, etc. 
- [ ] Substantive - objection to the guideline or change to its intent; recommendation to use another standard or service than what the guideline suggests; a major change to a process; etc. a major change to a process or  or use of a particular standard the 
- [ ] Question - Any question for clarity, scope, purpose, etc.

Section(s) of document referenced: C.1.

Comment/Question: Reference to SPD-41a should be updated when the policy is approved.

**Comment by nasacrawford** [comment]
Closed by merging #5
